healpy/healpy

healpy/__init__.py
healpy/pixelfunc.py
healpy/src/_healpy_pixel_lib.cc

Wrap additional functions `xyf2pix` and `pix2xyf`.

Add xyf2pix, pix2xyf

---

healpy/visufunc.py

Use integer division in visualization functions

---

healpy/fitsfunc.py
healpy/test/test_fitsfunc.py

This code has been tested and produces an output that is compatible with fits2alm.

write_alm can store a list of alms

---

ez_setup.py
healpy/pixelfunc.py
healpy/sphtfunc.py

finally got around to fix this.
@lpsinger I had to set `setuptools==12.0.5` in `requirements.txt`.
Do you think this could have implications for the install process?

Fixed build on readthedocs

---

healpy/fitsfunc.py

Add argument to write_map for extra header fields

---

healpy/test/test_sphtfunc.py

Relax tolerance for TestSphtFunc.test_rotate_alm

---

setup.py

Correctly parse PKG_CONFIG variable on non-POSIX systems

---

healpy/fitsfunc.py
healpy/test/test_fitsfunc.py

Not tested yet since I'm having issues compiling healpy on my machine, but hopefully Travis can do the testing :smile:

Allow read_map to also take an HDUList or HDU instance

---

healpy/pixelfunc.py

Allow ud_grade to work with read only maps.

---

.travis.yml
README.rst
setup.py

Drop support for Python 2.6

---

healpy/fitsfunc.py

AstroPy throws a DeprecationWarning when using header.update. This patch
updates fitsfunc so that it uses header.set or the header[key] = value
format instead

Change header.update to header.set or dict format

---

healpy/src/_healpy_sph_transform_lib.cc

updated healpix CXX to 786 (trunk)

---

healpy/src/_query_disc.pyx
healpy/test/test_query_disc.py

Reimplemented #271 with `np.can_cast` and `np.isscalar`

Boundaries list

---

.travis.yml
README.rst
healpy/fitsfunc.py
healpy/pixelfunc.py
healpy/test/test_query_disc.py
setup.py

Roll back #268 and #282 to preserve compatibility with Scientific Linux 6.

SL6 rollback

---

healpy/visufunc.py

Removes gnomview 'degree' argument

Issue287alt

---

.travis.yml

This should result in slightly faster builds on average.

In Travis, use Miniconda to install Cython and Astropy

---

healpy/visufunc.py

For demonstration, on python3 run:
```
import numpy as np
import healpy as hp
m = np.arange(12)
hp.mollview(m, sub=221)
hp.mollview(m, sub=222)
hp.mollview(m, sub=223)
hp.mollview(m, sub=224) 
```

Ensure subplots are placed correctly (python3 compatibility)

---

healpy/projector.py

Addresses issue #17, problem in gnomview when ysize is different xsize.

Consistent association of i,j with x,y in gnom axes

---

healpy/fitsfunc.py

This update function is invalid on current astropy and pyfits versions.
It is replaced with tbhdu.header[key] = (value, comment).
This shall fix #329.

Replace tbhdu.header.update(key, value, comment)

---

healpy/fitsfunc.py

See issue #340 .
I could not update the above issue itself with this PR, as I usually do with [hub](https://github.com/github/hub), possibly because I rebased ?
Anyhow, it's here.

Fix a benign unresolved reference.

---

setup.py

Update autotools source URLs for readthedocs

---

doc/index.rst
doc/license.rst

Adding the license to the docs pages

---

healpy/fitsfunc.py

We don't need this anymore because we use astropy now.

Remove unnecessary pyfits workaround

---

doc/healpy_query.rst
doc/index.rst

Document query_disc and friends

---

healpy/fitsfunc.py

This closes #395 (at least for the time being).

Added 'copy=False' to astype call in read_map

---

setup.py

Handle module __builtins__ both as dict or module

---

setup.py

This fixes #391 in a slightly cleaner way than #407.

Deal with nonuniform behavior of __builtins__ in Python 3

---

healpy/projector.py

See #322 
@gregreen can you please test my implementation?
even better if you have a quick test we can add to the unit tests.

Fix longitude bounds in cartview projection

---

healpy/fitsfunc.py

Make default FITS extensions names agree with HEALPix

---

setup.py

Add six to setup_requires

---

doc/healpy_spht.rst

Add the functions beam2bl and bl2beam to the documentation

Add beam2bl and bl2beam to the documentation

---

INSTALL.rst

Just trying to get my contributor tag for this great repo with minimal effort :)

fix minor typo in install instructions

---

healpy/projaxes.py

Allow custom `ListedColormaps` in the plotting functions.
Fixes https://github.com/healpy/healpy/issues/533

Allowed cmaps

---

healpy/__init__.py
healpy/fitsfunc.py
healpy/test/test_fitsfunc.py
healpy/test/test_rotator.py

Improve test coverage

---

RELEASE.md

Also includes a policy discussed with the HEALPix team

How to update the HEALPix C++ library

---

healpy/__init__.py
healpy/newvisufunc.py
healpy/pixelfunc.py
healpy/projaxes.py
healpy/projector.py
healpy/rotator.py
healpy/sphtfunc.py
healpy/test/test_fitsfunc.py
healpy/test/test_pixelfunc.py
healpy/test/test_query_disc.py
healpy/test/test_rotator.py
healpy/test/test_sphtfunc.py
healpy/test/test_spinfunc.py
healpy/visufunc.py
healpy/zoomtool.py

Add an `lmax` keyword for `hp.pixwin()`, as well as a couple of simple tests in `test_sphtfunc()`.
Addresses https://github.com/healpy/healpy/issues/536
Ran black formatting afterwards, hence the size of the PR.

Pixwin lmax

---

healpy/sphtfunc.py

@mreineck added docs about weighting, any feedback? thanks

add docs about weights

---

.travis.yml
CHANGELOG.rst
healpy/rotator.py
healpy/sphtfunc.py
healpy/test/test_pixelweights.py

@tskisner, do you think this is enough to fix https://github.com/healpy/healpy/issues/609 ?
Please send feedback also on the docs.

Check datapath for pixel weights

---

healpy/visufunc.py

fix: support input map None

---

CHANGELOG.rst

https://github.com/healpy/healpy/issues/592

update cfitsio to 3.47

---

healpy/sphtfunc.py
healpy/test/test_sphtfunc.py

Overflow getlm

---

healpy/src/_healpy_pixel_lib.cc

Fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964655.

Fix const correctness in Numpy ufunc API

---

healpy/projaxes.py
healpy/test/test_visufunc.py

Copy colormaps rather than altering in place. Note that if a user provides a colormap, it will also be copied. 
Closes #622

Copy colormaps

---

healpy/__init__.py
healpy/fitsfunc.py
healpy/pixelfunc.py
healpy/projaxes.py
healpy/rotator.py
healpy/sphtfunc.py
healpy/zoomtool.py

See https://github.com/healpy/healpy/issues/619#issuecomment-662212313

Rework verbose

---

healpy/fitsfunc.py
healpy/test/test_fitsfunc.py
healpy/test/test_sphtfunc.py

`pytest` was complaining (`ResourceWarning: unclosed file`) files were not closed by `read_map`, fixed that. 
Also, hit this `astropy` issue https://github.com/astropy/astropy/issues/10594, put a workaround converting `pathlib.Path` to `str`

Fix unclosed files 

---

healpy/rotator.py

See https://github.com/healpy/healpy/issues/247

Use astropy for coordinate transformations

---

setup.py

Fixes #18016. Inspired by numpy/numpy#18016.

Fix macOS Catalina build

---

healpy/sphtfunc.py

fix `bl2beam`: include lmax in the loop

---

healpy/__init__.py
healpy/pixelfunc.py

I added two convenience functions that map from resolution order to number of pixels and back.
The only thing that these functions do is call nside2npix(order2nside(order)) and nside2order(npix2nside(npix)).

Added convenice functions order2npix and npix2order.

---

healpy/sphtfunc.py

check beam_window is array or list.
This is #731 rebased on main to fix CI

Check beam window type

---

healpy/newvisufunc.py

This commit should solve the issue "Graticule rotation of projview #724". When the map is rotated, a rotated graticule can be turned on by using _rot_graticule=True_.  Also some properties of this graticule can be set, for instance color, linestyle, linewidth etc. The rotated graticule can be used along with the "normal" _graticule graticule=True_. I can add example of this to the JN.

Implementing the rotatable graticule.

---

healpy/__init__.py
healpy/sphtfunc.py
healpy/test/test_sphtfunc.py

This aims to implement the alternative approach to Healpix map analysis discussed in #676 .
Please feel free to push improvements to documentation and suggested code changes!
Most specifically I may need help dealing with support for multiple maps and polarization.

Draft: least squares map analysis

---

CHANGELOG.rst

Update HEALPix sources, fix CFITSIO warnings

---

CHANGELOG.rst

I think these are the PRs that were missing in the changelog since the January release.

Update Changelog.txt to reflect merged PRs

---

INSTALL.rst

add a section about generating native binaries

---

healpy/rotator.py

Hi, I think there's a typo in __rmul__, maybe from copypaste of __mul__

typo in rmul

---

CHANGELOG.rst
healpy/__init__.py
healpy/sphtfunc.py
healpy/test/test_sphtfunc.py

add resize_alm function

---

.readthedocs.yml
INSTALL.rst
doc/environment.yml
setup.py

The latest versions of Numpy and Astropy already have.

Drop support for Python 3.7

---

.github/workflows/cibuildwheel.yml

Build wheels for aarch64 under emulation

---

CHANGELOG.rst
healpy/__init__.py
healpy/fitsfunc.py
healpy/pixelfunc.py
healpy/projaxes.py
healpy/rotator.py
healpy/sphtfunc.py
healpy/test/test_deprecation.py
healpy/utils/__init__.py
healpy/utils/deprecation.py
setup.py

- Add healpy-specific deprecation warning and decorators
- Use the new healpy decorators for deprecation

healpy deprecation

---

healpy/src/_hotspots.pyx
healpy/src/_line_integral_convolution.pyx
healpy/src/_masktools.pyx
healpy/src/_pixelfunc.pyx
healpy/src/_query_disc.pyx
healpy/src/_sphtools.pyx

See https://github.com/conda-forge/healpy-feedstock/pull/57.

Fix absolute imports in .pyx files

---

.readthedocs.yml
doc/environment.yml

See https://blog.readthedocs.com/migrate-configuration-v2/.

Update readthedocs configuration to v2

---

.readthedocs.yml

Note, please wait until the CI checks pass before merging.

Use a Conda-enabled Python distro for Readthedocs

---

.gitignore
.gitmodules
MANIFEST.in
RELEASE.md
clean.sh
setup.py

This source layout is more similar to Astropy affiliated packages.

Move vendored sources to cextern directory

---

lib/healpy/fitsfunc.py

- **doc: fix explanation of hdu argument**
- **doc: explain alm file format**

Improve docs of read_alm

---

lib/healpy/pixelfunc.py

Addresses Issue #959 
This is a very minor change, but may help someone else not fall into the trap I fell into. I'm not sure if it should reference [PySM3 documentation](https://pysm3.readthedocs.io/en/latest/#best-practices-for-model-execution).

Added ud_grade docstring note about power spectra

---

lib/healpy/newvisufunc.py

Add lonlat parameter in newprojplot

Add lonlat parameter in newprojplot

---

doc/healpy_spht.rst

`resize_alm` is a very useful tool for some task, so I propose to add it into docs so that usrs wouldn't have to write a new function to do that.

add resize_alm to docs

---

pyproject.toml

Build Healpy wheels for musl libc Linux distributions

---

CHANGELOG.rst
lib/healpy/pixelfunc.py
test/test_pixelfunc.py

- **added support for automatically adjusting latitudes within [-90, 90] range**
- **propagated change in automatic latitude conversion to ang2pix**
- **added support for scanning through pole on lonlat2thetaphi**
- **added unit tests for latauto and latbounce features in lonlat2thetaphi for array and scalar input**
- **Apply suggestions from code review**

adjusting latitudes lonlat2thetaphi
