- .gitignore
- MANIFEST.in
- pykg_config.py
- run_pykg_config.py
- setup.py
Previously, dependencies listed in `setup_requires` were available within other scripts running inside the setup directory. Now that setup eggs are downloaded to the `.egg` directory, it seems that we have to create a dummy `Distribution` object to get to scripts.
Also, the `pykg_config.py` script had to be renamed to avoid a name collision with the `pykg_config` package.
Fixes #216.
> Adapt to some changes in behavior of pkg_resources.run_script

- healpy/fitsfunc.py
- healpy/projaxes.py
- requirements.txt
As we have already done in a few other places. Also add missing dependency on six. Fixes #226.
> Replace xrange with six.moves.xrange to support Python 3

- healpy/fitsfunc.py
- healpy/test/test_fitsfunc.py
- healpy/test/test_pixelfunc.py
- setup.py
This is a batch of enhancements for `write_map` and some backward compatibility patches, all related to writing LIGO probability sky maps:
* support adding units to the FITS header for each column in the HEALPix map
* support writing gzip-compressed FITS files, even with old versions of pyfits
* some minor changes in numpy and pyfits usage to support older versions of these packages that come with Scientific Linux 6, the OS of several of the LIGO computing clusters
> LIGO enhancements to write_map

- healpy/fitsfunc.py
Use `pyfits.new_table()` instead of `pyfits.BinTableHDU.from_columns()`
because the former is present in the older versions of pyfits that are
available in SL6 and Debian Wheezy.
Note that `pyfits.new_table()` has been deprecated, but we are using it
in all of the other FITS-writing functions.
> Make write_alm compatible with older versions of pyfits

- healpy/rotator.py
Either strings or Unicode are fine. In fact, we probably don't even
need to check the type here because we check the value itself over
the next few lines.
> Accept any string-like type for coord argument

- INSTALL.rst
- README.rst
Also, clean up README.rst and INSTALL.rst a little.
Addresses #248.
> Add caveat about OpenMP build to README

- healpy/fitsfunc.py
- healpy/test/test_fitsfunc.py
Added support for reading and writing partial sky maps.
New keywords OBJECT and GRAIN are written by write_map, and an index column is added if partial=True.  read_map parses INDXSCHM, OBJECT and GRAIN to determine whether the map
is a full or partial sky map, and returns an UNSEEN-padded map if the input map is partial.  The field index begins from the first column after the pixel index.
This might be useful for #252 ?
> write_map and read_map support for partial sky maps

- healpy/sphtfunc.py
Removes the "invert" parameter from hp.sphtfunc.smoothing smoothalm and alm2map. Also removes invert parameter in calls to these functions.
> 	modified:   sphtfunc.py Removed unused "invert" parameter

- healpy/sphtfunc.py
In the spin-0 case, the sequence of maps is iterated but the element is not used. In addition, the lmax and mmax keywords are not propagated (and the mask stuff doesn't need to be iterated).
> Fix typo and missing keywords in the handling of a set of spin-0 maps.

- healpy/fitsfunc.py
- healpy/test/test_fitsfunc.py
If the field argument is explicitly None, read all the columns from the fits file.  The default behavior is still to read in the first field in the file.
> option to read all fields with read_map

- setup.py
On OpenSUSE, libraries are installed into `lib64` instead of `lib`. If
we build our own healpix_cxx library, then we need to remember to add
both `lib64` and `lib` to the `PKG_CONFIG_PATH`.
Reported by @bsesar.
> Look for pkgconfig files in either lib64 or lib

- healpy/projaxes.py
This prevents an exception at the line 
bins = long(min(data2.size/20, 5000))
> Python 3 compatibility: alias long to int

- healpy/fitsfunc.py
I've found the following two minor updates useful:
* raise a useful `ValueError` for empty partial map in `write_map`
* test alms with `cookbook.is_seq_of_seq` (instead of `isinstance`) in `write_alm`
> A few minor fixes for write_map and write_alm

- setup.py
When installing through pip and using the requirements file, pip makes two passes through the `setup.py` files of the packages (including healpy): the first pass is to obtain some info, through the `setup.py egg_info` command. 
In a clean environment, where numpy and Cython are not yet installed (e.g., a virtualenv), this result in an error, since `setup.py` unconditionally imports numpy and Cython. Using a conditional import, by testing the argument given to `setup.py`, allows one to install healpy in one go (`pip install healpy`) without first needing to install numpy and Cython separately. This also prevents problems when one runs e.g. `setup.py --help` in a clean environment.
More information can be found at the [pip issue tracker](https://github.com/pypa/pip/issues/25); the solution …
> Remove Cython & numpy dependencies when querying setup.py

- healpy/projector.py
Fixes issue #286 where points plotted with projplot on orthview appear in the wrong hemisphere.
> RWO: Typo fix to fix hemisphere in orthview projplot

- .gitmodules
Some of us are working behind company firewalls that
do not allow access to git:// protocols, thus making
it impossible to use these projects as is.
This commit changes to protocols from git:// to
https://.  New repository clones should work with the
new protocols just fine.
Existing repository clones will have to run:
git submodule sync
in order to copy the protocol changes from
.gitmodules to .git/config
> FIX: Switch submodule protocols from git to https

- setup.py
The healpix_cxx API has changed, and Healpy now requires healpix_cxx >= 3.30.0. When we attempt to locate preexisting builds of healpix_cxx using pkg-config, restrict to healpix_cxx >= 3.30.0. If this requirement is not satisfied, we fall back to build healpix_cxx ourselves.
Fixes #292.
> Restrict external HEALPix installations to >= 3.30.0

- healpy/src/_healpy_sph_transform_lib.cc
This patch should remove problematic C++11 features from the C++ sources in healpy.
Similar features are present in the sources of Healpix 3.30 itself; I'm currently working to remove them as well.
> avoid C++11 features

- doc/conf.py
- healpy/__init__.py
- healpy/projaxes.py
- healpy/sphtfunc.py
- setup.py
There are numerous conditional imports and setup.py special cases to support building on Read The Docs. These tend to mask the causes of user installation errors (see #295).
The RTD build environment does support installing C extensions, so these patches cause RTD to do a full build of Healpy. RTD does lack autotools, which still must be downloaded as a special case.
The method `Distribution.fetch_build_eggs()` does the same thing as setting `setup_requires`, but at a controllable point in the script. The following changes are made to handling build dependencies:
* If the Cython-generated source files are absent, then Cython is required at all phases, including if the user is just asking for `--help`, because Cython adds command line options to `setup.py`. Because we are now using …
> Remove special cases for imports and setup.py build phases

- healpy/pixelfunc.py
According to the Numpy changelog(http://docs.scipy.org/doc/numpy-dev/release.html):
> Default casting for inplace operations will change to ‘same_kind’ in Numpy 1.10.0.
This is indeed the case, and Numpy inplace operations such as `/=` now must have results that can be cast to the same size and type as the left-hand side.
This patch is a straightforward transformation of the inplace operations in `healpy.ud_grade`.
> Convert /= operations to comply with Numpy 1.10.0 casting rules

- healpy/src/_common.pxd
So that bad arguments to `healpy.query_polygon` don't crash the interpreter.
A similar fix may be needed for other functions in this module.
> Catch and re-raise "polygon is not convex" errors in Python

- README.rst
- healpy/fitsfunc.py
- healpy/sphtfunc.py
- healpy/test/test_fitsfunc.py
- healpy/test/test_sphtfunc.py
- setup.py
The [days of PyFITS are numbered](http://www.stsci.edu/institute/software_hardware/pyfits)...
> All of the functionality of PyFITS is now available in Astropy as the astropy.io.fits package, which is now publicly available. Although we will continue to release PyFITS separately in the short term, including any critical bug fixes, we will eventually stop releasing new versions of PyFITS as a stand-alone product. The exact timing of when we will discontinue new PyFITS releases is not yet settled, but users should not expect PyFITS releases to extend much past early 2014.
> Depend on Astropy instead of PyFITS for FITS support

- healpy/fitsfunc.py
Commit 29c7ff4777557754aa1cd163eb03d3a6133b5d03 removed `write_alm`'s ability to write multiple alms. This commit restores that functionality.
> Fix bug in write_alm

- healpy/fitsfunc.py
Replace the deprecated function `astropy.io.fits.new_table` with the newer `astropy.io.fits.BinTableHDU.from_columns`. The latter has been available since Astropy 0.3.
Fixes #341.
> Replace deprecated astropy.io.fits method

- README.rst
- doc/HOWTO_DOC
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- healpy/pixelfunc.py
- healpy/test/test_pixelfunc.py
This pull requests addresses #361 by adding an optional `lonlat` argument to allow `theta` and `phi` to be provided as longitude and latitude (in degrees) rather than co-latitude and longitude (in radians). The `lonlat` argument was added for `ang2pix`, `pix2ang`, `ang2vec`, `vec2ang`, `get_interp_val`, `get_interp_weights`, and `get_all_neighbours`. Documentation and unit tests were added, along with the utility functions `lonlat2thetaphi` and `thetaphi2lonlat`.
> Add 'lonlat' option to functions in 'pixelfunc'

- healpy/projector.py
I got a numpy warning when plotting with a MollWeide projection:
```
/usr/local/lib/python3.5/site-packages/numpy/core/numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
```
I chased this down to `projector.py`: `ysize` was used directly in `np.arange` and `np.ones`, despite being
a floating point number after division (in Pyton 3). This commit simply coerces `ysize` (and `xsize`) to an int momentarily for use in `np.arange` and `np.ones`.
<hr>
While this commit provides a very simple fix, I'm inclined to apply the integer coercion earlier. Unless I'm mistaken, there is no reason for `ysize` (or `xsize`) to a float. E.g.
```python
xsize = int(self.arrayinfo['xsize'])
ysize = xsize // 2
```
I would even consider …
> Force ysize as int in np.arange and np.ones

- healpy/fitsfunc.py
In python3, division operator, "/", produces floating point results even with integer inputs. This produces a warning when the result is used in place of an integer input further on. 
The pull request imports the python3 division and uses it for integer-valued division in fitsfunc.py.
Having the harmless warning removed helps debugging software that uses healpy. This is especially the case when a developer has filtered all warnings to issue exceptions with
```
import warnings
warnings.filterwarnings('error')
```
> Fix warning from floating point division of two integers

- healpy/src/_sphtools.pyx
- healpy/test/test_sphtfunc.py
This is a proof of concept/description of issue #363 regarding use_weights in map2alm.  I do not expect it is a complete solution.  It has not been tested with Python 2 (I do not have such a test environment) so it may break Python 2.  There are also other cases/assumptions which may be missing.  I do not know much about cython in general or strings+cython at all!
The general idea is that the Python string (datapath variable) is in one format and the C string (c_datapath) needs to be in bytes.  In Python 3 these are different formats and seem to not be automagically converted.
If datapath is a "normal" Python string (unicode and/or type str), then it can be encoded into bytes.  This is the first part of the patch.
If datapath is already in bytes then it is good for the C code, but not for …
> Fix for strings in Python 2/3

- healpy/pixelfunc.py
- healpy/src/_pixelfunc.pyx
Now `check_nside` and `isnsideok` accept a `nest` parameter,
default `False`, it checks that `nside` is a power of 2 only
if `nest=True`.
Closes #333 
@lpsinger @mreineck (@cdeil?) can you take a look at it?
> Remove NSIDE power of 2 restriction for RING

- CHANGELOG.rst
- healpy/fitsfunc.py
- healpy/test/test_fitsfunc.py
Changes to fitsfunc.py in 443855896acfbbc1602a96e55126b022c677a133 caused a change in write_map() behavior. Prior, trying to write to a file that already existed caused the file to be silently overwritten.
After the change, write_map throws an IOError when the user attempts to write to an existing file. The only way to avoid the error is to check for the file existence and remove it before write_map().
It seems unnecessary to require users to check file existence every time they write a map. This pull request implements a keyword argument to write_map() called "overwrite". The current default behavior (fail when file exists) can be retained by setting overwrite=False by default. Defaulting it to True would restore the old default behavior and not require packages that depend on Healpy to …
> Add overwrite keyword to write_map

- healpy/pixelfunc.py
I keep getting a warning because of this comparison. None should be checked using "is" rather than "==".
> Fix deprecated comparison that will fail in the future

- healpy/fitsfunc.py
- healpy/rotator.py
- healpy/test/test_sphtfunc.py
The rotate_alm method in healpy/src/_sphtools.pyx mentions a helper routine, coordsys2euler_zyz that can be used to obtain the euler angles corresponding to a coordinate system transformation. However, the routine does not exist in Healpy but is rather implemented only in the Healpix Fortran library. This pull request implements the missing routine.
The angles are needed because the Cython interface does not expose the rotation matrix version of rotate_alm in the C++ library. The rotation matrices are a separate class in the C++ library that would need to be exported to use the C++ routines directly. It is much more straightforward to convert the rotation matrices into Euler angles in the Python side.
This pull request also adds the "overwrite" keyword to write_cl (to mirror write_map), …
> Coordsys2euler zyz

- healpy/fitsfunc.py
- healpy/pixelfunc.py
- healpy/sphtfunc.py
- healpy/src/_sphtools.pyx
- healpy/test/test_fitsfunc.py
- healpy/test/test_sphtfunc.py
This pull request addresses #113. All multi-component map and alm return values are changed into 2D numpy arrays instead of tuples. For the user, the change is mostly transparent as the 2D arrays handle like tuples in almost all cases. The tuple concatenation (referenced in #113) is an exception and demonstrates that the 2D array behavior is more intuitive. 
The change makes it unnecessary to cast the maps and alms into arrays in the client side for basic operations like addition and multiplication and should result in cleaner client code.
There is one use of read_map that may break existing codes. When the header is requested (h=True), old read_map would return a tuple of map components and the header appended last. The new code returns a 2-element tuple: (map, header) regardless of the …
> Tuple2array

- healpy/projaxes.py
- healpy/test/test_visufunc.py
This pull request fixes an error that caused mollzoom to throw an exception. 
When calling mollzoom with a partial sky and hist=True, an error was generated if the stamp at the center of the sky contained no valid pixels. Similar issues would have been caused by other projections when the viewable sky contained no valid pixels.
The pull request also adds relevant unit tests and fixes trivial white space issues in the affected files.
> Fix mollzoom crash

- healpy/pixelfunc.py
- healpy/sphtfunc.py
- healpy/src/_sphtools.pyx
- healpy/test/test_sphtfunc.py
This commit adds the gal_cut keyword to `anafast` and `map2alm` in sphtfunc.py. The same keyword was already supported by a number of methods in pixelfunc.py such as `remove_dipole`. Galactic cut is also supported by the IDL interface to anafast as `theta_cut_deg`.
The pull request also fixes a side effect in `map2alm` in _sphtools.pyx. The input map was being copied if and only if it was not contiguous 64bit float and pixels close to the UNSEEN value were set to zero and then to UNSEEN. While this may be desirable, it is unexpected for the map to be altered in place and even possibly slightly altered upon return.
The pull request also implements a unit test for map2alm with the galactic cut.
> Add gal_cut keyword to anafast and map2alm

- .gitignore
- healpy/fitsfunc.py
@lpsinger - This is just to follow up to https://github.com/healpy/healpy/pull/387#issuecomment-340307854 , I grepped `healpy` that there are no other cases where you have `==None` except for this one.
> Compare to None using is instead of ==

- healpy/pixelfunc.py
Checks the validity of the nside for `hp.pix2ang()`, address #420 .
> Add nside test for pix2ang.

- healpy/__init__.py
- healpy/sphtfunc.py
- healpy/test/test_sphtfunc.py
Small modification to allow to pass custom beam window functions like e.g. matched filters to the smoothing routines in sphtfunc.py. Adds new optional variable beam_window to sphtfunc.smoothing and sphtfunc.smoothalm.
Second commit adds translations of the healpix functions beam2bl and bl2beam. These functions allow transformations of beams to window functions and vise versa.
> Add beam_window variable to smoothing routines in sphtfunc.py

- healpy/test/conftest.py
Numpy's string representation of arrays changed significantly from 1.13 to 1.14. See the [changelog]. We have to set the legacy representation mode for our doctests to be reproducible across both old and new versions of Numpy.
There is a lingering issue with the doctest for `hp.reorder` that is due to a regression in Numpy. See numpy/numpy#11112.
[changelog]: https://docs.scipy.org/doc/numpy-1.14.0/release.html#many-changes-to-array-printing-disableable-with-the-new-legacy-printing-mode
> Make docstrings reproducible with bleeding-edge versions of Numpy

- healpy/src/_pixelfunc.pyx
This addresses issue #439, it only changes the documentation.  It includes 
- ring must be a 1d numpy array
- Change example to use complete, valid range of ring numbers
> Documentation fix for ringinfo

- healpy/pixelfunc.py
See:
- https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=arm64&ver=1.10.3-4&stamp=1527055920&raw=0
- https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=ppc64el&ver=1.10.3-4&stamp=1527057719&raw=0
> Fix precision of doctest for non-amd64 archs

- healpy/sphtfunc.py
- healpy/src/_sphtools.pyx
- healpy/test/test_pixelweights.py
Implementation of #356.
* Automatically download pixel weights file the first time `map2alm` is used with a specific nside using `astropy.data`
* Apply them before the call to the `map2alm` transform
> map2alm pixel weights

- healpy/pixelfunc.py
- healpy/test/test_pixelfunc.py
Added optional 'degrees' argument to pixelfunc.max_pixrad (with associated test) to address #452.
> Optional degrees argument for max_pixrad

- README.rst
We removed python 3.4 from the CI matrices a while ago, it was causing some trouble. That should be reflected in the docs.
> Remove python 3.4 from supported versions

- healpy/src/_sphtools.pyx
- healpy/test/test_sphtfunc.py
This address https://github.com/healpy/healpy/issues/474 by actually using the `lmax_out` keyword. 
Right now, I've only truncated the full Cl that we get from `hp.alm2Cl()`. Ideally, we might want to adjust the loop to only go to `lmax_out` instead of `lmax`, but I was somewhat confused by the mixed use of `lmax` and `lmax_`.
Happy to have that reviewed and corrected!
> Actually use lmax_out keyword for alm2cl

- setup.py
Update the minimum version of healpix-cxx in the pkg-config check. The healpix-cxx API changed in version 3.40.0, and we now require that version to build healpy. If the user has an older version of healpix-cxx installed, then we should use our own bundled sources instead.
This may address #455, #465.
> Update minimum healpix-cxx version

- setup.py
It is imported by `healpy.sphtfunc`.
> Add missing dependency on scipy

- healpy/__init__.py
- healpy/sphtfunc.py
- healpy/test/test_sphtfunc.py
Most of the functions in sphtfunc.py are only implemented for nside <= 8192. This PR ensures a graceful exit in case the nside is too large.
Address https://github.com/healpy/healpy/issues/484
> Add max_nside test to sphtfunc.py functions

- healpy/sphtfunc.py
Sporadic test failures have been reported by the Debian project.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907908.
> Set random seed to make test_rotator reproducible

- healpy/test/test_visufunc.py
- healpy/visufunc.py
- healpy/zoomtool.py
Addresses #482 
Nested maps are only defined for nsides that are a power of 2. This is caught, but not in the python layer. This PR allows a graceful exit with a meaningful error in e.g. notebooks and ipython.
> Add nside tests for all visu funcs, needed for nested maps.

- healpy/visufunc.py
This commit adds the Boolean no_plot variable to the gnomview function in visufunc.py. Setting the variable to True will close the automatically generated output figure, which is useful is gnomview is run in a loop i.e. when stacking a large number of maps. Without this option, healpy will consume large amounts of RAM and can crash jupyter notebooks.
> Add no_plot Boolean variable to gnomview

- setup.py
Fixes #505.
After merging this, we should do another release and rebuild the wheels.
> Declare support for Numpy >= 1.13

- healpy/rotator.py
- healpy/src/_common.pxd
- healpy/src/_sphtools.pyx
- healpy/test/test_rotator.py
- healpy/test/test_sphtfunc.py
* Added support in `hp.rotate_alm` for rotation matrices, originally healpy only wrapped the version of the function with angles (this was reported in #399)
* Renamed the `rotate_map` function to `rotate_map_pixel` as it is working in pixel space
* Added new function `rotate_map_alms` that does the rotation in harmonics space, see discussion in #460 
See an example: https://gist.github.com/zonca/67a0fec459de5b9bed007f1ec071a4b5
@ziotom78 would you like to provide some feedback?
> Rotate map in spherical harmonics space

- healpy/sphtfunc.py
Reverts healpy/healpy#487
I'm guessing this wasn't meant to make it into production (at least not in this way), since it means synfast always produces the same map?
CC @lpsinger 
https://xkcd.com/221/ :)
> Revert "Set random seed to make test_rotator reproducible"

- .travis.yml
2 configurations fail with hard to debug errors, skipping them.
> skip Python 2.7 tests failing on Travis

- healpy/pixelfunc.py
Hi, 
this pull-request fixes the doc string of pix2ang and vec2ang in pixelfunc module, where
the output angles are given in reverse order.
Cheers,
Eric
> fix pix2ang and vec2ang doc string

- doc/conf.py
- doc/create_images.py
- healpy/fitsfunc.py
- healpy/projaxes.py
- healpy/sphtfunc.py
- healpy/test/test_fitsfunc.py
- healpy/test/test_pixelfunc.py
- healpy/test/test_pixelweights.py
- healpy/test/test_query_disc.py
- healpy/test/test_rotator.py
- healpy/test/test_sphtfunc.py
- healpy/test/test_spinfunc.py
- healpy/visufunc.py
- setup.py
The preferred way to handle paths in python>=3.4 is by using pathlib.
```python
from pathlib import Path
path = Path('/home/data/')
hpxmap = hp.read_map(
path.joinpath('myfile.fits')
)
```
If we try to use hp.read_map() with a `Path` instance, it is not parsed correctly and an exception is raised:
`TypeError: First argument should be a input_data, HDUList instance, or HDU instance`
This PR addresses this; astropy.io.fits already supports pathlib, I just had to add a `Path` instance to the allowed types for `pf.read()`.
> Add support for pathlib

- healpy/pixelfunc.py
A Numpy string formatting bug causes this doctest to fail on
certain 32-bit platforms (e.g. armhf). The bug is evident in the
following example:
>>> np.arange(8)
array([0, 1, 2, 3, 4, 5, 6, 7])
>>> 1 << np.arange(8)
array([  1,   2,   4,   8,  16,  32,  64, 128], dtype=int32)
The `dtype=int32` should be supressed in both cases, but it is not.
This might get fixed upstream in Numpy 1.17. See numpy/numpy#9799,
numpy/numpy#10151.
> Work around Numpy formatting glitch in doctest

- healpy/pixelfunc.py
- healpy/src/_healpy_pixel_lib.cc
- healpy/test/test_pixelfunc.py
All of the pixel ufuncs use Healpix_Base2, which has 64 bit pixel
indices. However, it declares arguments as longs, which are not
necessarily a 64 bit data type (on armhf, they are 32 bit).
Fixing this allows us to manipulate 64 bit pixel indices even on
32 bit machines.
> Fix incorrect data types in pixel ufuncs

- healpy/pixelfunc.py
Checking for `__len__` attribute is not enough to check if the object is sized
> Fix issue #526

- healpy/pixelfunc.py
Some unit tests were failing on i386 due to the slightly different default rounding behavior with the old x87 floating point instructions set. Add a small offset to make the test give the same answer on both i386 (a.k.a. x86) and amd64 (a.k.a. x86_64).
Fixes #528.
> Add offset to test inputs for reproducibility on i386

- doc/tutorial.rst
Minimal solution to address https://github.com/healpy/healpy/issues/538.
I'd furthermore prefer to have a function that loads test data and puts them into the package directory for future use. One example for this is implemented e.g. in [sklearn.datasets.fetch_datasets](https://scikit-learn.org/stable/datasets/index.html#real-world-datasets).
Feel free to comment/merge as needed for JOSS, I'd still like to extend/update the tutorial in the near future.
> Add download instructions for high-res WMAP data

- healpy/projaxes.py
- healpy/visufunc.py
Users can set the color map used to plot the Healpix maps but they have no way to adjust the way the background and UNSEEN pixels are plotted.
This pull request adds two keyword parameters to mollview, orthview, gnomview and azeqview:
* badcolor to set the value used to plot bad values
* bgcolor to set the value of the background
both of these values default to the current library defaults: "gray" for UNSEEN values and "white" for background.
> Allow user to set the background and UNSEEN colors in calls to *view()

- healpy/fitsfunc.py
read_map forces input to a specific dtype, by default double.
Now if dtype is None, it maintains the original dtype.
> maintain the FITS dtype in read_map

- healpy/projaxes.py
Matplotlib 3.1 deprecated `matplotlib.cbook.iterable`, with `np.iterable` recommended as a direct replacement. This pull request makes said change, fixing the deprecation warning.
> Fix Matplotlib 3.1 deprecation warning

- healpy/projaxes.py
This completes the work from a previous merged pull request https://github.com/healpy/healpy/pull/563 by replacing the remaining matplotlib.cbook.iterable calls with np.iterable calls.
> Complete conversion of deprecated calls: matplotlib.cbook.iterable -> np.iterable.

- healpy/src/_sphtools.pyx
In _sphtools.alm_getlmax(int s),  the line x=(-3+np.sqrt(1+8*s))/2 results in a negative sqrt for very large sizes (starting at nside=8192). Casting to a float is an easy fix, but we should keep an eye out for similar issues as they'll occur more often in the near future.
Addresses https://github.com/healpy/healpy/issues/572
> Cast argument to sqrt to float to prevent overflow

- INSTALL.rst
Currently, the development install instructions ask to add 'healpy/healpy' to PYTHONPATH, but it is 'healpy' that needs to be added. This PR clarifies the docs.
> Fix for development install instructions in INSTALL.rst

- healpy/src/_pixelfunc.pyx
- healpy/src/_query_disc.pyx
- healpy/test/test_pixelfunc.py
- healpy/test/test_query_disc.py
Hi There,
This PR changes the isnsideok() function to allow non-power-of-two nside values (when using the RING scheme). This is useful when searching for a pixelization scheme that is just high enough - which can lead to huge efficiencies in the situation where one is discretizing a small subset of the sphere at high resolution.
The test is somewhat application specific (to suit my needs) so apologies in advance for that.
Refers to Issue #583.
Tim
> Allow non-power-of-two nside values when the pixel scheme is RING

- healpy/fitsfunc.py
- healpy/test/test_sphtfunc.py
related to #585 
I don't know the procedure how to make compatibility warnings (as @crosset suggested), but can add these as soon as someone has told me :).
> try to make dtype defaults more consistent

- setup.py
Fixes #576.
This should work but for the two issues mentioned in #576 that must first be fixed in the HEALPix svn repository.
> Update healpix-cxx to 3.60

- MANIFEST.in
- healpy/__init__.py
- healpy/src/_healpy_hotspots_lib.cc
- healpy/src/_healpy_hotspots_lib.h
- healpy/src/_hotspots.pyx
- setup.py
This PR adds support for hotspot computation within healpy. This was something already in Healpix/F90 code since years as well as in Healpix/C++ (see [hotspots_cxx_module.cc](https://github.com/healpy/healpixmirror/blob/29d2a54dde968a4e71bdb06c193f607f0b98168a/src/cxx/Healpix_cxx/hotspots_cxx_module.cc)) but only as an executable for the latter. 
The PR wraps the C++ code in a `cython` file given its implementation as an "independant" library. I also post the corresponding C++ code which is just a copy-paste of the original code from `hotspots_cxx_module.cc` (see the following [gist](https://gist.github.com/xgarrido/7333c6686ca913f5365d92fd79ef4151)). It will need to be added to Healpix/C++ code, so @mreineck or any one else, feel free to amend it.
Btw, this PR will fix the #493 issue.
> Add hotspot support in healpy

- healpy/sphtfunc.py
Pixel weights at NSIDE 8192 are too large to be added to
the `healpy-data` repo, had to attach them to a release.
See https://github.com/healpy/healpy-data/issues/1
> Support download of pixel weights at NSIDE 8192

- doc/tutorial.rst
Changed "maptlotlib" to "matplotlib"
> Fixed misspelling in tutorial.rst

- healpy/sphtfunc.py
In current `master`, smoothing with `mmax !=lmax` fails:
```
In [1]: import healpy as hp                                                                                                                                                           
In [2]: hp.smoothing(np.arange(12*8**2),lmax=8,mmax=3)                                                                                                                                
Sigma is 0.000000 arcmin (0.000000 rad) 
-> fwhm is 0.000000 arcmin
Sigma is 0.000000 arcmin (0.000000 rad) 
-> fwhm is 0.000000 arcmin
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e0ab22460e8a> in <module>
----> 1 …
```
> Fix propagation of mmax in smoothing

- .travis.yml
- INSTALL.rst
- conftest.py
Useful for Travis, uses `pytest-astropy-header`
but does not fail if that is missing.
Closes #448
> Report version of dependencies under test

- healpy/pixelfunc.py
- setup.cfg
- setup.py
This fixes a unit test failure on Debian i386:
https://buildd.debian.org/status/fetch.php?pkg=healpy&arch=i386&ver=1.13.0-2&stamp=1594306120&raw=0
- Add a test dependency on Astropy's pytest-doctestplus.
- Add the FLOAT_CMP doctest option flag to flaky tests.
> Fix floating point comparison failures in doctests

- INSTALL.rst
This solves installation issues due to conflict between MacOSx Catalina and conda install.
The command line example I added to the installation doc (with an explanation of the issue) results in a clean install (tested on my MacBook .
> Add MacOSX Catalina installation issues workaround to docs.

- MANIFEST.in
- doc/healpy_line_integral_convolution.rst
- doc/index.rst
- healpy/__init__.py
- healpy/src/_line_integral_convolution.pyx
- healpy/src/_line_integral_convolution_lib.cc
- healpy/src/_line_integral_convolution_lib.h
- healpy/src/_sphtools.pyx
- healpy/test/test_line_integral_convolution.py
- healpy/visufunc.py
- setup.py
This pull request adds line integral convolution support based on the `alice3` executable from Healpix 3.60.
Since `alice3` is structured as a standalone executable, I copied the C++ code and modified it such that it could be called as a function from Cython, although refactoring the code upstream to support both uses would have been another possibility.
The other main change made is to add an option to the visualization functions to allow the current axes to be reused. When combined with a partially transparent colormap, this allows the LIC output to be plotted over another map.
I also fixed a compilation bug I came across in `_sphtools.pyx`, which I believe is related to the default language level change in Cython 3.0.
Here's an example of the new functionality:
```python3
import numpy …
```
> Add support for line integral convolution (LIC)

- setup.py
`test_pixelweights.py` imports `requests`, so it should be in `setup.py`'s list of requirements: https://github.com/healpy/healpy/blob/master/healpy/test/test_pixelweights.py#L3
Before this, I was unable to run `python setup.py test`. It works after this change.
> Add requests to tests_require list

- doc/create_images.py
- doc/healpy_tutorial.ipynb
- doc/tutorial.rst
- healpy/fitsfunc.py
- healpy/pixelfunc.py
- healpy/projaxes.py
- healpy/src/_pixelfunc.pyx
- healpy/src/_query_disc.pyx
- healpy/test/test_sphtfunc.py
The np.bool and np.float types have been deprecated in numpy 1.20 and
the correct versions have been available for a very long time.
> Replace np.bool with np.bool_ and np.float with np.float64

- pyproject.toml
- setup.py
This will make it easier to build wheels.
> Replace antiquated cython detection with PEP 518 dependency spec

- healpy/fitsfunc.py
LIGO/Virgo probability maps sometimes set OBJECT to an integer to indicate an event ID:
https://git.ligo.org/lscsoft/ligo.skymap/-/blob/v0.5.0/CHANGES.rst#L11-13
> Do not assume that OBJECT is a string

- CHANGELOG.rst
- healpy/sphtfunc.py
I suggest implementing a new "nest" parameter in healpy.sphtfunc.smoothing() so that when the input map is in NESTED ordering, the function takes care of reordering it to RING for the smoothing and back to NESTED before the output. I have tried to follow the way "nest" argument where used in other Healpy functions, but maybe the description in the docstring can be improved and maybe the ordering back to NESTED can be removed and you could just specify that healpy.sphtfunc.smoothing() will return a RING ordered map no matter the input. 
I hope this helps a bit or at least serves as a base to improve the clarity of the smoothing function.
> Suggestion of a new nest parameter in healpy.smoothing() 

- CHANGELOG.rst
- healpy/sphtfunc.py
I think we shouldn't change this, better keep supporting both ways keeping the same default we have now.
> Remove note that we will change order in synalm and synfast

- CHANGELOG.rst
- doc/alpha_channel_example.ipynb
- doc/other_tutorials.rst
- healpy/newvisufunc.py
- healpy/projaxes.py
- healpy/visufunc.py
Following from #684
- Added alpha channel in visualization
- Updated docstring with the alpha channel
- fix: alpha is already None
- format with black
> Support for alpha channel in visualization

- healpy/fitsfunc.py
- healpy/pixelfunc.py
- healpy/projaxes.py
- healpy/projector.py
- healpy/src/_line_integral_convolution.pyx
- healpy/src/_query_disc.pyx
- healpy/test/test_pixelweights.py
- healpy/test/test_sphtfunc.py
This PR replaces all instances of the [deprecated numpy aliases](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) with the appropriate (identical) builtin. This should have absolutely zero functional impact, but will remove a bunch of `DeprecationWarning`s for users of `numpy >=1.20.0`.
> Replace all deprecated numpy aliases with builtins

- doc/healpy_spht.rst
- healpy/__init__.py
- healpy/sphtfunc.py
This PR imports the `map2alm_spin` and `spin2alm_map` functions into the `sphtfunc` module, and also adds them to the documentation. Closes #701.
> add spin functions to sphtfunc module and doc

- CHANGELOG.rst
- healpy/src/_sphtools.pyx
- healpy/test/test_spinfunc.py
CC @zonca @mreineck 
This flips the signs for spin 0 transforms `alm2map_spin` and `map2alm_spin`.
Note that there was an existing `test_spin0` that checked the other sign convention specifically.
> reimplement spin 0 transforms

- CHANGELOG.rst
- healpy/fitsfunc.py
- healpy/test/test_fitsfunc.py
Until the last release (1.14.0), whatever precision a map is in memory, it is written to disk in single precision (`float32`) and when read, it is converted to double precision (`float64`). As was written in the warning, now instead `healpy` will maintain whatever precision the map is in both when reading and writing.
I am a bit worried that a user upgrading is not notified about this, it is in the docstring and the changelog but there is no other notification, any suggestions here?
> Change default for read_map and write_map

- healpy/fitsfunc.py
Closes #709.
(Note that the map used in the issue is not in healpix format and `npix2nside` rises an error. I tried in another maps and works)
> fixes #709: get nside from length of array

- healpy/cookbook.py
- healpy/sphtfunc.py
This PR makes it so that `synalm` accepts Cls that are `None` at the Python layer. Closes #700.
```py
>>> hp.synalm([[1.], None, None, None, None, None], new=True)
array([[-0.14311095+0.j],
[ 0.        +0.j],
[ 0.        +0.j]])
```
> accept `None` cls for synalm

- .github/workflows/cibuildwheel.yml
Be sure to checkout cibuildwheel 2.0 when it comes out, as the new config mode will let you move most of the config into pyproject.toml!
> chore: cibuildwheel has joined the pypa

- healpy/cookbook.py
- healpy/sphtfunc.py
- healpy/test/test_cookbook.py
There are situations in which `synalm()` breaks when called with a single cl with entries that are not plain numbers, but objects that have a `__len__` function. This happens naturally when e.g. the cl is generated in a framework such as JAX, and can be simulated using 0-dimensional numpy arrays:
```py
>>> cl = [np.zeros(shape=())]*4
>>> cl
[array(0.), array(0.), array(0.), array(0.)]
```
The reason for the failure is that the `is_seq_of_seq` check tests for the `__len__` function, which the entries of the cl now have:
```py
>>> hp.cookbook.is_seq_of_seq(cl)
True
```
In `synalm()`, the single cl passes through to the code which deals with lists of cls, and when `len(c) for c in cl` is called, the `len()` of the 0-dimensional arrays raises an error (same as e.g. within JAX):
```py
>>> …
```
> check is_seq by calling len()

- CHANGELOG.rst
- healpy/sphtfunc.py
@ntessore following https://github.com/healpy/healpy/pull/595#issuecomment-935792362
`healpy` has already this functionality, I improved the docs, please review them,
can you also make a test to make sure it works as advertised?
We also have a unit test on this: https://github.com/healpy/healpy/blob/c632a318fecc3ae020f6b5367e024e8927c4df4c/healpy/test/test_pixelweights.py#L37-L52
> docs: improve docs on datapath for pixel weights

- .github/workflows/cibuildwheel.yml
- pyproject.toml
The cibuildwheel CI job is timing out. Skip wheels for 32-bit archs (i686). These archs are very rare nowadays and it is not common for our upstream dependencies to provide wheels for them anyway. Numpy, for example, does not distribute i686 wheels.
This should significantly reduce the build time because the CI job will only have to build half as many wheels. The skipped i686 wheels were the slowest anyway, because it had to build wheels for many of the dependencies too (including Numpy).
> Only build wheels for 64-bit archs (skip i686)

- healpy/test/test_visufunc.py
- healpy/visufunc.py
It's come to my attention that when I wrote #617, I apparently forgot to actually test `reuse_axes=True` for `cartview` and `gnomview`, since it never actually worked in these cases and threw an exception instead. This PR fixes those mistakes and also adds tests to prevent future regressions for this.
> Fix `reuse_axes=True` for `cartview` and `gnomview`

- CHANGELOG.rst
- healpy/visufunc.py
See further discussion in #756.
For `mollview`, `orthview`, and `azeqview`, the `margins` parameter previously did not do anything when subplot syntax was not used.
For `mollview`, `gnomview`, `cartview`, `orthview`, and `azeqview`, the `margins` parameter was previously double applied when subplot syntax was used.
This PR fixes both issues. Note that with the change in margin behavior, the output of existing scripts that use the `margins` parameter may change.
> Fix plot margins

- healpy/projaxes.py
Closes #765. Stop normalizing binary arrays. 
However, it is unclear to me what should happen if one of the values is not 0. Ideas?
> Do not normalize binary arrays (issue765)

- .github/workflows/cibuildwheel.yml
According to the [README](https://github.com/pypa/gh-action-pypi-publish):
> The master branch version has been sunset. Please, change the GitHub Action version you use from master to release/v1 or use an exact tag, or a full Git commit SHA.
> Switch to gh-action-pypi-publish release

- healpy/newvisufunc.py
Right now the projview function still does one figure-related operation even if return_only_data is set to True. This change stops that from happening by moving that call inside a check.
> Move projview's subplots_adjust inside check on return_only_data

- .github/workflows/cibuildwheel.yml
- pyproject.toml
The gcc version on GitHub's macos-latest runners has been updated.
This fixes an error in which the macOS wheel build would fail with the error message, "C compiler cannot create executables".
See #794.
> Update gcc compiler for macOS cibuildwheel

- healpy/newvisufunc.py
Hi, I propose small changes for `newvisufunc`, which allow one to better locate the colorbar label for `geographic` (for `cb _orientation='vertical'`) and `cartesian` (for both `cb_orientation` cases) projections.
For me it is the first experience with pull request, please let me know if something should be done differently.
> Fixed colorbar label for newvisfunc (cartesian and geographic proj)

- .github/workflows/cibuildwheel.yml
- pyproject.toml
GitHub has retired macOS 10.15 support.
> Bump macOS version used for wheel builds

- .github/workflows/cibuildwheel.yml
This will eliminate manual dependabot update PRs for patch releases of cibuildwheel.
See https://github.com/pypa/cibuildwheel/pull/1517
> Use moving minor tag for cibuildwheel

- .github/workflows/cibuildwheel.yml
Fix this warning from gh-action-pypi-publish:
Warning: Input 'packages_dir' has been deprecated with message: The inputs have been normalized to use kebab-case. Use `packages-dir` instead.
> Fix kebab case warning

- .readthedocs.yml
- pyproject.toml
See https://numpy.org/neps/nep-0029-deprecation_policy.html.
> Drop support for Python 3.8

- pyproject.toml
- setup.py
From Numpy 1.25 onward, Numpy has API backwards compatibility. It is no longer necessary to build against oldest-supported-numpy.
> Build against numpy 1.25, not oldest-supported-numpy

- pyproject.toml
- run_pykg_config.py
- setup.py
This stopped working in Python 3.12.
> Don't use deprecated pkg_resources package to find pykg-config

- .github/workflows/cibuildwheel.yml
GitHub just announced free Apple Silicon runners for open-source projects: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
Fixes #835.
> Build wheels for macOS arm64

- .github/workflows/cibuildwheel.yml
- pyproject.toml
https://github.com/healpy/healpy/pull/896 accidentally switched
the macOS builds form gcc to Xcode's clang; this disabled OpenMP on
macOS because the Xcode's clang does not support the `-fopenmp` flag.
Since gcc was causing crashes on macOS 14 (see
https://github.com/matplotlib/matplotlib/issues/27724), switch from
gcc to homebrew's clang, which does support OpenMP and does not
cause crashes.
> Move cibuildwheel conf to pyproject.toml, fix OpenMP for macOS

- pyproject.toml
Setuptools no longer recommends this. See
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#basic-use
> Remove wheel from build-system requires

- pyproject.toml
- setup.py
Move as much of the build configuration as possible from setup.py to pyproject.toml.
> Move packages, package data, and scripts to pyproject.toml

- .gitmodules
- pyproject.toml
- setup.py
Cfitsio links against libcurl to support remote file I/O. On Linux, curl adds 24 shared libraries totalling 11 MB in size that get bundled into the wheel.
Nowadays, remote I/O support for FITS reading in Python is not provided by cfitsio but by the Python code in astropy.io.fits.
It's unlikely that the cfitsio remote file I/O was working anyway because the default certificate paths baked into the libraries are unlikely to match their locations on the target system, and there is no way to control those paths from the Python-level API.
> Shrink wheels by not linking against libcurl

- .gitmodules
- Update bundled cfitsio to 4.3.1.
- Use official GitHub mirror maintained by HEASARC instead of our own mirror.
> Update bundled cfitsio to 4.3.1, use official GH mirror

- healpy/__init__.py
- healpy/sphtfunc.py
- healpy/visufunc.py
- healpy/zoomtool.py
- pyproject.toml
Made `scipy` and `matplotlib` optional dependencies, where they can be included by doing `pip install "healpy[all]"`.  Addresses https://github.com/healpy/healpy/issues/907
The `scipy` dependency was simple, and moving it to the function level was trivial. However for `matplotlib`, custom `healpy` classes inherit directly from `matplotlib` classes, thus simply moving the imports to the function level wasn't possible. In order to have a _semi-stable_  library, I had to remove the `visfunc`, `zoomtool`, and `newvisfunc` imports from `healpy/__init__.py`. Which means that users will have to call those methods by descending into those modules directly (e.g. `healpy.visfunc.mollview(...)`).
- Upsides: 
- Importing `healpy` will be much faster.
- Installing sans `scipy` and `matplotlib` will be …
> Optional dependencies

- pyproject.toml
pytest-cython does not work with pytest 8.x. See lgpage/pytest-cython#58.
Fixes #912.
> Fix pytest-cython errors by requiring pytest<8

- pyproject.toml
This reduces the unzipped size of the package by 3.4 MB.
> Exclude C, C++, and Cython sources from wheels

- healpy/test/test_fitsfunc.py
- healpy/test/test_pixelfunc.py
- healpy/test/test_sphtfunc.py
- healpy/test/test_spinfunc.py
Nowadays, we always run these tests with pytest.
> Remove unittest module runner

- pyproject.toml
setuptools_scm has updated the recommended package verisons for build-system.requires.
> Update build-system.requires settings

- healpy/test/conftest.py
This is no longer necessary, because we require Numpy >= 1.19.
> Remove conftest code for Numpy < 1.13

- pyproject.toml
Numpy 2.0.0 is coming out soon. In order to support both Numpy 1.x and 2.x, we must build against Numpy 2.x.
The [official guidance from Numpy](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling) is that we should be targeting numpy 2.0.0rc1 as a build dependency now.
> Build against Numpy>=2.0.0rc1

- lib/healpy/projaxes.py
- src/_line_integral_convolution.pyx
- test/test_visufunc.py
The `matplotlib.cm.get_cmap` API was deprecated in 3.7, and removed in 3.9, but `matplotlib.pyplot.get_cmap` remains.
> Fix errors with Matplotlib 3.9

- .github/workflows/cibuildwheel.yml
I use this approach for publishing wheels in https://github.com/nasa/radbelt.
> Extract artifacts in the dir where twine expects them

- lib/healpy/sphtfunc.py
The fix should be backward compatible up to `scipy` 1.6.0 where the function first appears.
Fix #952
> Rename trapz function from scipy.integrate module to trapezoid

- .github/workflows/cibuildwheel.yml
- pyproject.toml
GitHub has retired their macOS 11 runners.
> Run macOS x86_64 builds on macOS 12

- setup.py
cfitsio's `make install` target weirdly does not depend on `make all`, so `make install` by itself doesn't install shared libraries.
> Ensure that we build cfitsio as a shared library

- INSTALL.rst
- README.rst
- doc/environment.yml
- pyproject.toml
In accordance with https://numpy.org/neps/nep-0029-deprecation_policy.html.
> Drop support for Python 3.9

- .github/workflows/cibuildwheel.yml
- pyproject.toml
macOS 12 is past end of life now.
> Update Mac x86_64 CI runner to macOS 13

- lib/healpy/sphtfunc.py
For large arrays `scipy.linalg.norm` overflows and gives 0 output:
```python
> norm(np.ones(int(2.5e9))*10)
0
```
`numpy`'s version of the function works fine.
> fix overflow in map2alm_lsq

- lib/healpy/newvisufunc.py
- lib/healpy/projaxes.py
- lib/healpy/rotator.py
- lib/healpy/visufunc.py
- lib/healpy/zoomtool.py
This pull request updates the documentation for coordinate system parameters, providing a clearer explanation of the available options ('E', 'G', and 'C') and their meanings (Ecliptic, Galactic, and Celestial/Equatorial). It also improves readability by integrating these definitions into the parameter description naturally. These changes aim to make the documentation more user-friendly and informative. Also solve issue #841.
> Improve docs on coordinate systems

- .github/workflows/cibuildwheel.yml
- pyproject.toml
This will result in faster builds.
> Build Linux aarch64 wheels natively, not under emulation

- pyproject.toml
See https://peps.python.org/pep-0639/#deprecate-license-classifiers.
> Remove deprecated license classifier

- pyproject.toml
This fixes the following warning:
```
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
```
> Use new style of pyproject.toml license field

- lib/healpy/sphtfunc.py
- test/test_pixelweights.py
Addresses issue #1015 by adding a try-except block around the pixel weights download in map2alm. If the download fails, a warning is logged and the function proceeds without using pixel weights. Also includes a new test case to verify this behavior.
> Fix: Handle pixel weights download failures in map2alm

- CHANGELOG.rst
- src/_query_disc.pyx
- test/test_pixelfunc.py
Minimal implementation and unit test for issue #843. This fixes the crash when calling query_strip with nest=True by internally converting to RING ordering, performing the query, and then converting the result back to NEST ordering if required.
> Fix #843: query_strip is not implemented for NESTED
